#!/usr/bin/env python
"""
compile_for_ai.py — Project State Compiler

Compiles the current project state into a single document for:
- Cross-tool transfer (moving context from one AI tool to another)
- Archival snapshots (recording project state at a point in time)
- Onboarding (bringing a new team member's AI up to speed)
- Context recovery (when conversation history is lost)

In an IDE-native workflow (VSCode/Roo, Cursor, Windsurf), the AI reads
files directly and does NOT need this for normal operation. Use this when:
1. Switching to a browser-based AI tool (ChatGPT, Claude web)
2. Creating an archival record of project state
3. The project exceeds the AI's ability to read piecemeal
4. Onboarding a collaborator

Output: prompts/compiled_for_ai.md
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# === CONFIGURATION ===
MAX_FILE_CHARS = 10000
MAX_TOTAL_CHARS = 150000


def get_project_root():
    """Get the project root directory (parent of scripts folder)."""
    return Path(__file__).parent.parent


def read_file_safely(filepath, max_chars=MAX_FILE_CHARS):
    """Read a file, truncating if necessary."""
    try:
        content = filepath.read_text()
        if len(content) > max_chars:
            content = content[:max_chars] + f"\n\n[... TRUNCATED - {len(content)} total chars ...]"
        return content
    except Exception as e:
        return f"[Error reading file: {e}]"


def find_scripts(experiments_dir):
    """Find all experiment scripts organized by phase."""
    scripts_info = []

    for phase_dir in sorted(experiments_dir.iterdir()):
        if phase_dir.is_dir() and not phase_dir.name.startswith('.'):
            scripts = sorted(phase_dir.glob("script_*.py"))
            for script in scripts:
                scripts_info.append({
                    'path': script.relative_to(get_project_root()),
                    'phase': phase_dir.name,
                    'content': read_file_safely(script)
                })

    return scripts_info


def find_recent_files(directory, pattern="*.md", count=5):
    """Find the most recent files in a directory."""
    if not directory.exists():
        return []
    files = sorted(directory.glob(pattern), key=lambda f: f.stat().st_mtime, reverse=True)
    return files[:count]


def compile_project():
    """Compile the entire project state into a single document."""
    root = get_project_root()
    output = []
    total_chars = 0

    # Header
    output.append("=" * 70)
    output.append("SMAIRT PROJECT STATE COMPILATION")
    output.append(f"Generated: {datetime.now().isoformat()}")
    output.append(f"Project: {root.name}")
    output.append("")
    output.append("This file was generated by scripts/compile_for_ai.py")
    output.append("Use it to bring an AI assistant up to speed on the full project state.")
    output.append("=" * 70)
    output.append("")

    # === KEY CONTEXT FILES ===
    key_files = [
        ("prompts/AI_CONTEXT.md", "AI Context (Your Role)"),
        ("prompts/CODE_CONVENTIONS.md", "Code Conventions"),
        ("prompts/KNOWN_PATTERNS.md", "Known Patterns & Common Errors"),
        ("prompts/CONTEXT_INDEX.md", "Context Index"),
        ("prompts/intellectual_contribution.md", "Intellectual Contributions"),
        ("background/01_initial_question.md", "Initial Research Question"),
    ]

    output.append("")
    output.append("#" * 70)
    output.append("# KEY CONTEXT FILES")
    output.append("#" * 70)

    for filepath, description in key_files:
        full_path = root / filepath
        if full_path.exists():
            content = read_file_safely(full_path)
            output.append("")
            output.append(f"## {description}")
            output.append(f"## File: {filepath}")
            output.append("-" * 50)
            output.append(content)
            output.append("")

            total_chars += len(content)
            if total_chars > MAX_TOTAL_CHARS:
                output.append(f"\n[TRUNCATED - Reached {MAX_TOTAL_CHARS} character limit]")
                break

    # === PLANS (Active) ===
    if total_chars < MAX_TOTAL_CHARS:
        plans_dir = root / "plans"
        if plans_dir.exists():
            plan_files = find_recent_files(plans_dir, "*.md", count=5)
            if plan_files:
                output.append("")
                output.append("#" * 70)
                output.append("# ACTIVE PLANS (most recent 5)")
                output.append("#" * 70)

                for plan in plan_files:
                    content = read_file_safely(plan, max_chars=5000)
                    output.append("")
                    output.append(f"## {plan.name}")
                    output.append("-" * 50)
                    output.append(content)
                    output.append("")
                    total_chars += len(content)
                    if total_chars > MAX_TOTAL_CHARS:
                        break

    # === RECENT HYPOTHESES ===
    if total_chars < MAX_TOTAL_CHARS:
        hyp_dir = root / "hypotheses"
        if hyp_dir.exists():
            hyp_files = find_recent_files(hyp_dir, "HYPOTHESIS_*.md", count=5)
            if hyp_files:
                output.append("")
                output.append("#" * 70)
                output.append("# RECENT HYPOTHESES (most recent 5)")
                output.append("#" * 70)

                for hyp in hyp_files:
                    content = read_file_safely(hyp, max_chars=3000)
                    output.append("")
                    output.append(f"## {hyp.name}")
                    output.append("-" * 50)
                    output.append(content)
                    output.append("")
                    total_chars += len(content)
                    if total_chars > MAX_TOTAL_CHARS:
                        break

    # === RECENT ANALYSIS ===
    if total_chars < MAX_TOTAL_CHARS:
        analysis_dir = root / "analysis"
        if analysis_dir.exists():
            analysis_files = find_recent_files(analysis_dir, "ANALYSIS_*.md", count=5)
            if analysis_files:
                output.append("")
                output.append("#" * 70)
                output.append("# RECENT ANALYSIS (most recent 5)")
                output.append("#" * 70)

                for analysis in analysis_files:
                    content = read_file_safely(analysis, max_chars=5000)
                    output.append("")
                    output.append(f"## {analysis.name}")
                    output.append("-" * 50)
                    output.append(content)
                    output.append("")
                    total_chars += len(content)
                    if total_chars > MAX_TOTAL_CHARS:
                        break

    # === EXPERIMENT SCRIPTS ===
    if total_chars < MAX_TOTAL_CHARS:
        experiments_dir = root / "experiments"
        if experiments_dir.exists():
            output.append("")
            output.append("#" * 70)
            output.append("# EXPERIMENT SCRIPTS")
            output.append("#" * 70)

            scripts_info = find_scripts(experiments_dir)

            for script in scripts_info:
                output.append("")
                output.append(f"## {script['path']}")
                output.append(f"## Phase: {script['phase']}")
                output.append("-" * 50)
                output.append("```python")
                output.append(script['content'])
                output.append("```")
                output.append("")

                total_chars += len(script['content'])
                if total_chars > MAX_TOTAL_CHARS:
                    output.append(f"\n[TRUNCATED - Reached {MAX_TOTAL_CHARS} character limit]")
                    break

    # === SHARED LIBRARY ===
    if total_chars < MAX_TOTAL_CHARS:
        shared_dir = root / "scripts" / "shared"
        if shared_dir.exists():
            shared_files = list(shared_dir.glob("*.py"))
            if shared_files:
                output.append("")
                output.append("#" * 70)
                output.append("# SHARED LIBRARY")
                output.append("#" * 70)

                for sf in sorted(shared_files):
                    content = read_file_safely(sf, max_chars=5000)
                    output.append("")
                    output.append(f"## scripts/shared/{sf.name}")
                    output.append("-" * 50)
                    output.append("```python")
                    output.append(content)
                    output.append("```")
                    output.append("")
                    total_chars += len(content)
                    if total_chars > MAX_TOTAL_CHARS:
                        break

    # === RECENT LOGS ===
    if total_chars < MAX_TOTAL_CHARS:
        logs_dir = root / "results" / "logs"
        if logs_dir.exists():
            logs = sorted(logs_dir.glob("*.log"), key=lambda f: f.stat().st_mtime, reverse=True)[:5]

            if logs:
                output.append("")
                output.append("#" * 70)
                output.append("# RECENT OUTPUT LOGS (last 5)")
                output.append("#" * 70)

                for log in logs:
                    content = read_file_safely(log, max_chars=5000)
                    output.append("")
                    output.append(f"## {log.name}")
                    output.append("-" * 50)
                    output.append(content)
                    output.append("")

                    total_chars += len(content)
                    if total_chars > MAX_TOTAL_CHARS:
                        output.append(f"\n[TRUNCATED - Reached {MAX_TOTAL_CHARS} character limit]")
                        break

    # Footer
    output.append("")
    output.append("=" * 70)
    output.append("END OF COMPILATION")
    output.append(f"Total characters: {total_chars}")
    output.append("=" * 70)

    return "\n".join(output)


def main():
    """Main entry point."""
    compiled = compile_project()

    root = get_project_root()
    output_path = root / "prompts" / "compiled_for_ai.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(compiled)

    print(f"Project state compiled successfully!")
    print(f"Output: {output_path}")
    print(f"Total characters: {len(compiled)}")
    print()
    print("Use cases:")
    print("  1. Cross-tool transfer — paste into a browser-based AI")
    print("  2. Archival — snapshot the project state")
    print("  3. Onboarding — bring a collaborator's AI up to speed")
    print()
    print("Note: In IDE-native AI (Roo/Zoo, Cursor), the AI reads files")
    print("directly and does NOT need this for normal operation.")
    print()
    print("To copy to clipboard (Mac):  cat prompts/compiled_for_ai.md | pbcopy")
    print("To copy to clipboard (Linux): cat prompts/compiled_for_ai.md | xclip -selection clipboard")


if __name__ == "__main__":
    main()
